using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System;
//using UnityEngine;

namespace PaperRealm.Type.Fitur
{
    public class Shuffler
    {
        // System.Random instance to ensure better randomness and flexibility
        private Random random = new Random();

        // Shuffles the list using OrderBy and a random key
        public List<int> ShuffleListWithOrderBy(List<int> list)
        {
            // OrderBy each element with a random key generated by System.Random
            return list.OrderBy(x => random.Next()).ToList();
        }
    }
}
